# Generated by Django 2.2.24 on 2021-07-28 13:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Czas na ukończenie')),
                ('required_score_to_pass', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Wymagana liczba punktów')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=254, verbose_name='Treść pytania')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Poprawna odpowiedź')),
                ('answer_one', models.CharField(max_length=255, verbose_name='Odpowiedź')),
                ('answer_two', models.CharField(max_length=255, verbose_name='Odpowiedź')),
                ('answer_three', models.CharField(max_length=255, verbose_name='Odpowiedź')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz', verbose_name='Quiz')),
            ],
        ),
    ]
