# Generated by Django 2.2.24 on 2021-08-10 10:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Tytuł')),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Czas na ukończenie')),
                ('required_score_to_pass', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Wymagana liczba punktów')),
                ('is_published', models.BooleanField(default=False, verbose_name='Czy opublikowany?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor quizu')),
            ],
            options={
                'verbose_name_plural': 'Quizes',
            },
        ),
        migrations.CreateModel(
            name='QuizResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_start', models.DateTimeField()),
                ('quiz_end', models.DateTimeField(null=True)),
                ('results', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Liczba punktów')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=254, verbose_name='Treść pytania')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Poprawna odpowiedź')),
                ('answer_one', models.CharField(max_length=255, verbose_name='Odpowiedź')),
                ('answer_two', models.CharField(max_length=255, verbose_name='Odpowiedź')),
                ('answer_three', models.CharField(max_length=255, verbose_name='Odpowiedź')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', related_query_name='question', to='quiz.Quiz', verbose_name='Quiz')),
            ],
        ),
    ]
